### ISSUE TITLE
[Question] Manually mapping query result to struct

### ISSUE THREAD

**Issue by marianozunino** [stephenafamo/bob#166]
First of all, thanks for such an amazing project :heart: 

I really enjoy the DX.

I been working with Jet for a while now, and I really enjoyed it.

Now, when it comes to inserting/updating I like way more your approach of 
having the `SetterStruct` that "detects" if values were indeed changed
or not.

On the other hand Jet allows me to manually create joins between tables
and map that to the "models".

I would like to know if; that is something that I can do with Bob?
I know I can fetch relations with the provided methods, but I would love to avoid doing two queries when I have a one->many relation.

**Comment by stephenafamo** [comment]
First, I want to say that Jet allows preloading one->many relations without multiple queries because it converts the records to JSON on the DB and unmarshals it.  
While this would work in many case, this can lead to subtle bugs when converting rows to/from JSON, for example:
* I believe the JSON spec tops out at 32bit integers, so transmitting large numbers may be an issue.
* If you use custom types that implement `database/sql.Scanner` this would not be used since it is now a JSON unmarshal operation.

These are the reasons why `Bob` only does "Preloading" with `to-one` records where the extra columns are scanned from the database in the same way as one would expect.



Second, can you give an example of what **exactly** you do in Jet that you would like to be able to do in Bob?  
I think I have some idea, but help me better understand 🙏🏾

**Comment by marianozunino** [comment]
Hey! Didn't know that Jet was using to map the result into the struct. Good to know, thanks.

Here is what I'm doing with Jet:
```go
	stmt := SELECT(
		table.Worker.AllColumns,
		table.Schedule.AllColumns,
		table.WorkingHour.AllColumns,
	).FROM(
		table.Worker.
			INNER_JOIN(table.Schedule, table.Worker.ScheduleID.EQ(table.Schedule.ID)).
			INNER_JOIN(table.WorkingHour, table.Schedule.ID.EQ(table.WorkingHour.ScheduleID)),
	)

	var dest []struct {
		model.Worker
		Schedule struct {
			model.Schedule
			WorkingHours []struct {
				model.WorkingHour
			}
		}
	}

	stmt.Query(db.DB, &dest)
```

and this would be the Bob equivalent, of course, way shorter. I don't mind about writing close to sql like the Jet way. 
But the following statement will issue a left join and then a select as the documentation says.


```go
	return models.Workers.Query(
		ctx,
		store.Executor,
		models.PreloadWorkerSchedule(
			models.ThenLoadScheduleWorkingHours(),
		),
	).All()
```

**Comment by stephenafamo** [comment]
> But the following statement will issue a left join and then a select as the documentation says

Yes, at the moment, there is no way to load all of these relationships in a single query with the generated models.

Now, if you want, you could recreate the exact query that Jet generates using bob's query builder, but you would have to write the scanner manually which can get really tedious. If you want to give it a go, take a look at [the scan package](https://github.com/stephenafamo/scan), which is what Bob uses under the hood.
