### ISSUE TITLE
Invalid code generation for PostgreSQL BYTEA 

### ISSUE THREAD

**Issue by HTechHQ** [stephenafamo/bob#192]
Hello, I am just exploring bob for the first time.

My database schema has a column of type `BYTEA` and the generated code fails with the following compiler error
`invalid operation: new.Key != old.Key (slice can only be compared to nil)`

It is in the `ReloadAll` method of the slice type of the corresponding table.

I've temporarily replaced the line `if new.Key != old.Key {` with `if !reflect.DeepEqual(new.Key, old.Key) {` and at least get the program to compile.

**Comment by stephenafamo** [comment]
Thanks for reporting this.

The issue is that `BYTEA` columns are mapped to `[]byte` and I'm guessing you're using this column as your primary key, so it tries to do a comparison to know which model is for which row.

While `reflect.DeepEqual` would work, I wouldn't want to use reflection in such a hot path as it isn't very performant.

Instead, I would rather use [slices.Compare](https://pkg.go.dev/slices#Compare) when the primary key type is a slice.

**Comment by HTechHQ** [comment]
I just double checked, and you are right the primary key is of type `BYTEA` and the generated code maps this to `[]byte`.
I use other columns with type `BYTEA` in the same table as well, not sure if this is of relevance.

Totally understand the concern about reflect, it was just my first time testing bob and didn't want to abandon my exploration at this early stage.
It would be nice if the code generator handles this, otherwise it gets overwritten each time.

**Comment by stephenafamo** [comment]
@HTechHQ can you try #204 and confirm that is solves your issue?

**Comment by HTechHQ** [comment]
It works for me. The new code compiles without issue.
Thank you for the fix!
