### ISSUE TITLE
Global db handle, panic on error, no context

### ISSUE THREAD

**Issue by MeanSquaredError** [stephenafamo/bob#20]
It seems that Bob does not support three features which SQLBoiler supports, namely:

- Methods that do not receive a database handle with each call, instead they use a global database handle that is set once via `boil.SetDB()`.
- Methods that do not return an error, but just `panic()` on error.
- Methods that do not receive a context, instead they are uninterruptible and behave the same way as if a context-aware method has been called with a context returned by `context.Background()`.

I see that these features are not listed as unsupported SQLBoiler features, so I wonder if there are plans to add support for them?

**Comment by stephenafamo** [comment]
I should list them as having no plans to support.

I consider all 3 of these anti-patterns. And considering the complexity that they add to the templates I would have to write and maintain, I would rather not.

### Global DB

This makes it hard to test, makes it impossible to work with transactions, e.t.c.

### Panic

Not the recommended way of error handling in Go. Since the underlying DB calls return errors, Bob should pass those errors up. The user can selectively panic where they want.

### Context requirement

Since `context` was added to Go, the DB drivers are expected to use them too and so I think Bob should promote that behaviour.

When a user wants to add things like tracing and observability (in addition to shutdown signalling), context makes it really simple.

## Alternatives

Over the past few commits, I've improved the workflow of adding custom templates so one could write this for themselves.

In addition, it should be easy to create and reuse packages to modify the bob generation or add their own templates, maybe some level of ecosystem arises from it.

For this reason, I *may* consider creating these functionality in a separate package.  
This should work for adding global and panic variants, but will likely not work for `context`. For what it's worth, SQLBoiler intends to remove `--no-context` in `v5` anyway.

**Comment by MeanSquaredError** [comment]
OK, thank you for the information.
