### ISSUE TITLE
Allow code generation to be used as a library

### ISSUE THREAD

**Issue by jalaziz** [stephenafamo/bob#311]
We wrap bobgen code generation in our own CLI tool that automatically spins up an ephemeral postgres container and runs migrations before running bobgen.

While this works and has saved us quite a bit of repetitive manual effort, managing the version of bobgen to match the version of bob used as a dependency is somewhat annoying. It would be great if we could simply use bobgen as a library such that we can simply use the bobgen version from the version of `bob` in our `go.mod`.

While this is technically doable today by simply copying the `run` function from the relevant bobgen `main.go`, the code doesn't seem stable; so a simple, semi-stable interface would be very much welcome. Additionally, when trying to use bobgen as a library, the "version" in the generator header is simply `(devel)`.

**Comment by stephenafamo** [comment]
> While this is technically doable today by simply copying the `run` function from the relevant bobgen `main.go`, the code doesn't seem stable

Actually........... it is mostly stable and I wish people would do this more. Most of the changes to drivers happen in the `driver` package.

There are several advantages to this:

1. No need to have the configuration in `bobgen.yaml`. You can write your configuration directly in your code.   
    This will also remove the need to use `bobgen-helpers`.
1. You can use plugins. For example, in a project, I use this to generate some GraphQL code for my models. (still need to document this).



> Additionally, when trying to use bobgen as a library, the "version" in the generator header is simply `(devel)`.

This is because I rely on getting the go module version, which Go sets to `devel` when running directly.  
You can overwrite the generator through the config to whatever you like 🤷🏾‍♂️
