### ISSUE TITLE
Headless code generation

### ISSUE THREAD

**Issue by hiendaovinh** [stephenafamo/bob#32]
I would love to have the model generation, query builder and type-safety and related stuff without a bob.Executor for the sake of manual SQL execution.
Is that possible to generate headless stubs that return query builder with models generated?
From there, we could `Build` them and execute them at our will.
Thank you.

**Comment by stephenafamo** [comment]
You can use it as a simple query builder without any changes.

For example, you could do 

```go
q := models.Users(ctx, nil) // this implements the bob.Query interface

// So we can do this
raw, args, err := bob.Build(q)
```

You will only get a panic if you use `One`, `All`, `Count` e.t.c.


___

### Backstory

In earlier versions of Bob, you didn't need to supply the context or the executor until calling `One` or `All`, e.t.c.  
And so we could just use it as a query builder without any of the finishers.

The reason it is supplied early for multi-tenant scenarios.

While it is not documented yet, it is possible to use Bob in a multi-tenant scenario and use the context to dynamically change the schema.  
For example, imagine a schema where every tenant has a set of tables with the same name under different schemas and we want to change which schema we are querying for at runtime.

But for this to work, the context is required at the beginning of the query to pass to `psql.Table.Name`. While the executor is not needed at the start of the query building, since the context is eventually passed to the executor, it feels like they should always be passed together.

**Comment by hiendaovinh** [comment]
Thanks for your help!

**Comment by stephenafamo** [comment]
Something to note.

Using it this way, loading and preloading would not work as expected.  
These only work when using `bob.One`, `bob.All` and `bob.Cursor`.
 

More accurately, preloading would require scanning into a struct that can handle all the returned columns, while loading with a new query will not work at all.

**Comment by hiendaovinh** [comment]
Totally understandable!

**Comment by hiendaovinh** [comment]
@stephenafamo Sorry for being hasty but I don't think we could access ViewQuery{q} with this :sob: 
```go
models.Users(ctx, nil)
```

The query construction is not really flexible when using `...bob.Mod[*dialect.SelectQuery]` instead of step-by-step crafting

**Comment by stephenafamo** [comment]
What I do is to collect all the mods using `mods.QueryMods` (any slice will do) and then pass it to `models.Users()`

**Comment by stephenafamo** [comment]
Perhaps it will be elegant to have an `Apply` method on the query

**Comment by hiendaovinh** [comment]
> What I do is to collect all the mods using mods.QueryMods (any slice will do) and then pass it to models.Users()

That's what I'm doing but it's not really fun anymore :laughing: 

> Perhaps it will be elegant to have an Apply method on the query

I'm looking for this :+1:

**Comment by stephenafamo** [comment]
> Perhaps it will be elegant to have an `Apply` method on the query

@hiendaovinh this is now available on `master` (no release yet).

Along with `Apply()`, there are now methods for `Build()`, `Exec()` on the query itself.  
In summary, the View embeds `bob.BaseQuery` so it gets a number of useful methods, although `Apply` was re implemented to handle preloaders well.
