### ISSUE TITLE
Relationship struct field tag options

### ISSUE THREAD

**Issue by miniscruff** [stephenafamo/bob#41]
Trying to adjust the json tags of the relationship fields a little. For the complete context we are trying to build a JSON response that looks sort of like:
```json
{
  "id": "stuff",
  "name": "dave",
  "cars"(no way to edit this value): [{
      "id": "car id",
      "user_id": "user id",
      "make": "honda",
      "year": 2020
  }]
}
```

Where b would be a one to many relationship. 

Given a configuration like this:
```yaml
tags: ["json"]
relation_tag: ",inline" # this should build a single inline JSON of relational data
```

Here are two tables that I think illustrate the issue:
```sql
CREATE TABLE user (
    id serial PRIMARY KEY,
    name varchar(255),
)
    
CREATE TABLE cars (
    id serial PRIMARY KEY,
    user_id INT NOT NULL REFERENCES user(id),
    make varchar(255),
    year INT
);
```

The output would be something along the lines of:
```go
// userR is where relationships are stored.
type userR struct {
    Cars CarsSlice `json:"Cars" db:"Cars" json:"Cars" toml:"Cars" yaml:"Cars"`
    // first issue is JSON is duplicated ( maybe due to my tags config? )
    // next I would like the option to customize the value inside the tag ( in this case to be cars, lower case )
    // ideal, should match the base model json tag
    Cars CarsSlice `json:"cars"`
}
```

Let me know if that made sense or if you have questions, I can also take a look at the code base myself.

**Comment by stephenafamo** [comment]
1. The duplicate tags are a bug. Fixed by 8104434
2. The `relation_tag` configuration affects what the tag for the `R` field on the base model will be. By default, it is `-`. 
3. There are currently no configuration options to modify the tags of the relationships.

**Comment by miniscruff** [comment]
> 1. The duplicate tags are a bug. Fixed by [8104434](https://github.com/stephenafamo/bob/commit/8104434c952b3c0d1c855d77386ae6964bd22286)
> 
>     2. The `relation_tag` configuration affects what the tag for the `R` field on the base model will be. By default, it is `-`.
> 
>     3. There are currently no configuration options to modify the tags of the relationships.

Oh cool, I just need to update to fix the first one.

Yea, I set mine to "inline" but that doesn't do what I remember, so ignore that comment I guess. What I am trying to do is flatten the resulting JSON by removing the `R` field. By default its not serialized ( eg `json:"-"` ), but I do want the relationships include when getting but without the extra layer if possible.

I might be able to help with the third point if there is a design in place

**Comment by stephenafamo** [comment]
AFAIK, the only way to flatten a field with `encoding/json` is to embed the struct.

Doing this in Bob will also mean having to export the relationship struct type, and also have a lot of implications for Bob as a whole.

One considerable implication is that the method to query related options will have to change. Right now, to query the cars of a user, one would do 


```go
user, _ := model.FindUser(ctx, db, 1)
cars, _ := user.Cars(ctx, db).All()
```

Because the `user.Cars` method exists, even if we embed the relationship struct, we will **always** have to access loaded relationships by doing `user.UserR.Cars`.

Alternatively, we could rename the method for querying relationships, but then the changes start affecting even more things.

**Comment by stephenafamo** [comment]
Additionally, if you want to marshal the relationship struct, you should likely add the configuration options

```yaml
no_back_referencing: true
```

Because when relationships are loaded, they are added to the `.R` field on both sides.  
If `R` is not ignored, then it could lead to an infinite loop when marshalling.

Of course, turning off back referencing also creates some limitations, but nothing too bad IMO.

**Comment by miniscruff** [comment]
Hmm, yea, that all sounds like it would change quite a bit. 

What about some option for creating custom methods on the generated types to build a custom "MarshalJSON" implementation? All the work with json tags and customization is purely to edit any marshal or unmarshal work. Maybe either a custom template or config that wouldn't effect any generation with it disabled. 

Would still need to turn off back referencing I believe to avoid the infinite loop you are talking about

**Comment by stephenafamo** [comment]
The easy way would be to add extra templates by sort of creating your own generation script. I'm going to add some documentation about this but it should be possible to take a look at one of the generation drivers and see. `bobgen-psql` is like 15 lines long 😂 

There is some discussion about it on #34 about custom templates in general, and #37 about additional methods specifically

**Comment by miniscruff** [comment]
I will take a look when I can, any docs would be helpful for sure.
